<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.4
 *   protoc               — v6.33.5
 * Source: google/type/datetime.proto
 */

declare(strict_types=1);

namespace Google\Type\DateTime;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class TimeOffsetUtcOffset implements \Google\Type\DateTime\TimeOffset
{
    /**
     * @param ?\Google\Protobuf\Duration $utcOffset UTC offset. Must be whole seconds, between -18 hours and +18 hours.
     * For example, a UTC offset of -4:00 would be represented as
     * { seconds: -14400 }.
     */
    public function __construct(
        #[Reflection\Field(8, new Reflection\ObjectT(\Google\Protobuf\Duration::class))]
        public ?\Google\Protobuf\Duration $utcOffset = null,
    ) {}
}
