<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: google/type/datetime.proto
 */

declare(strict_types=1);

namespace Google\Type\DateTime;

/**
 * @api
 * @phpstan-sealed (
 *   TimeOffsetUtcOffset |
 *   TimeOffsetTimeZone
 * )
 */
interface TimeOffset {}
