<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.0
 *   protoc               — v6.33.5
 * Source: google/type/datetime.proto
 */

declare(strict_types=1);

namespace Thesis\Google\Type\DateTime;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class TimeOffsetTimeZone implements \Thesis\Google\Type\DateTime\TimeOffset
{
    /**
     * @param ?\Thesis\Google\Type\TimeZone $timeZone Time zone.
     */
    public function __construct(
        #[Reflection\Field(9, new Reflection\ObjectT(\Thesis\Google\Type\TimeZone::class))]
        public ?\Thesis\Google\Type\TimeZone $timeZone = null,
    ) {}
}
