<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.20
 *   protoc               — v6.33.5
 * Source: google/type/phone_number.proto
 */

declare(strict_types=1);

namespace Google\Type\PhoneNumber;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class KindE164Number implements \Google\Type\PhoneNumber\Kind
{
    /**
     * @param string $e164Number The phone number, represented as a leading plus sign ('+'), followed by a
     * phone number that uses a relaxed ITU E.164 format consisting of the
     * country calling code (1 to 3 digits) and the subscriber number, with no
     * additional spaces or formatting, e.g.:
     *  - correct: "+15552220123"
     *  - incorrect: "+1 (555) 222-01234 x123".
     *
     * The ITU E.164 format limits the latter to 12 digits, but in practice not
     * all countries respect that, so we relax that restriction here.
     * National-only numbers are not allowed.
     *
     * References:
     *  - https://www.itu.int/rec/T-REC-E.164-201011-I
     *  - https://en.wikipedia.org/wiki/E.164.
     *  - https://en.wikipedia.org/wiki/List_of_country_calling_codes
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $e164Number = '',
    ) {}
}
