<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.0
 *   protoc               — v6.33.5
 * Source: google/type/phone_number.proto
 */

declare(strict_types=1);

namespace Thesis\Google\Type\PhoneNumber;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class KindShortCode implements \Thesis\Google\Type\PhoneNumber\Kind
{
    /**
     * @param ?\Thesis\Google\Type\PhoneNumber\ShortCode $shortCode A short code.
     *
     * Reference(s):
     *  - https://en.wikipedia.org/wiki/Short_code
     */
    public function __construct(
        #[Reflection\Field(2, new Reflection\ObjectT(\Thesis\Google\Type\PhoneNumber\ShortCode::class))]
        public ?\Thesis\Google\Type\PhoneNumber\ShortCode $shortCode = null,
    ) {}
}
