<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.20
 *   protoc               — v6.33.5
 * Source: google/type/phone_number.proto
 */

declare(strict_types=1);

namespace Google\Type\PhoneNumber;

/**
 * @api
 * @phpstan-sealed (
 *   KindE164Number |
 *   KindShortCode
 * )
 */
interface Kind {}
