<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: google/type/phone_number.proto
 */

declare(strict_types=1);

namespace Google\Type\PhoneNumber;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * An object representing a short code, which is a phone number that is
 * typically much shorter than regular phone numbers and can be used to
 * address messages in MMS and SMS systems, as well as for abbreviated dialing
 * (e.g. "Text 611 to see how many minutes you have remaining on your plan.").
 *
 * Short codes are restricted to a region and are not internationally
 * dialable, which means the same short code can exist in different regions,
 * with different usage and pricing, even if those regions share the same
 * country calling code (e.g. US and CA).
 */
final readonly class ShortCode
{
    /**
     * @param string $regionCode Required. The BCP-47 region code of the location where calls to this
     * short code can be made, such as "US" and "BB".
     *
     * Reference(s):
     *  - http://www.unicode.org/reports/tr35/#unicode_region_subtag
     * @param string $number Required. The short code digits, without a leading plus ('+') or country
     * calling code, e.g. "611".
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $regionCode = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $number = '',
    ) {}
}
