<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.18
 *   protoc               — v6.33.5
 */

declare(strict_types=1);

\Thesis\Protobuf\Registry\Pool::get()->register(
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Type\GoogleTypeCalendarPeriodDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Type\GoogleTypeColorDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Type\GoogleTypeDateDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Type\GoogleTypeDatetimeDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Type\GoogleTypeDayofweekDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Type\GoogleTypeDecimalDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Type\GoogleTypeExprDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Type\GoogleTypeFractionDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Type\GoogleTypeIntervalDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Type\GoogleTypeLatlngDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Type\GoogleTypeLocalizedTextDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Type\GoogleTypeMoneyDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Type\GoogleTypeMonthDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Type\GoogleTypePhoneNumberDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Type\GoogleTypePostalAddressDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Type\GoogleTypeQuaternionDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Google\Type\GoogleTypeTimeofdayDescriptorRegistry()),
);
