<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/type/calendar_period.proto
 */

declare(strict_types=1);

namespace Google\Type;

/**
 * @api
 *
 * A `CalendarPeriod` represents the abstract concept of a time period that has
 * a canonical start. Grammatically, "the start of the current
 * `CalendarPeriod`." All calendar times begin at midnight UTC.
 */
enum CalendarPeriod: int
{
    /** Undefined period, raises an error. */
    case CALENDAR_PERIOD_UNSPECIFIED = 0;

    /** A day. */
    case DAY = 1;

    /**
     * A week. Weeks begin on Monday, following
     * [ISO 8601](https://en.wikipedia.org/wiki/ISO_week_date).
     */
    case WEEK = 2;

    /**
     * A fortnight. The first calendar fortnight of the year begins at the start
     * of week 1 according to
     * [ISO 8601](https://en.wikipedia.org/wiki/ISO_week_date).
     */
    case FORTNIGHT = 3;

    /** A month. */
    case MONTH = 4;

    /**
     * A quarter. Quarters start on dates 1-Jan, 1-Apr, 1-Jul, and 1-Oct of each
     * year.
     */
    case QUARTER = 5;

    /** A half-year. Half-years start on dates 1-Jan and 1-Jul. */
    case HALF = 6;

    /** A year. */
    case YEAR = 7;
}
