<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.0
 *   protoc               — v6.33.5
 * Source: google/type/date.proto
 */

declare(strict_types=1);

namespace Google\Type;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Represents a whole or partial calendar date, such as a birthday. The time of
 * day and time zone are either specified elsewhere or are insignificant. The
 * date is relative to the Gregorian Calendar. This can represent one of the
 * following:
 *
 * * A full date, with non-zero year, month, and day values
 * * A month and day value, with a zero year, such as an anniversary
 * * A year on its own, with zero month and day values
 * * A year and month value, with a zero day, such as a credit card expiration
 * date
 *
 * Related types are [google.type.TimeOfDay][google.type.TimeOfDay] and
 * `google.protobuf.Timestamp`.
 */
final readonly class Date
{
    /**
     * @param int $year Year of the date. Must be from 1 to 9999, or 0 to specify a date without
     * a year.
     * @param int $month Month of a year. Must be from 1 to 12, or 0 to specify a year without a
     * month and day.
     * @param int $day Day of a month. Must be from 1 to 31 and valid for the year and month, or 0
     * to specify a year by itself or a year and month where the day isn't
     * significant.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int32T::T)]
        public int $year = 0,
        #[Reflection\Field(2, Reflection\Int32T::T)]
        public int $month = 0,
        #[Reflection\Field(3, Reflection\Int32T::T)]
        public int $day = 0,
    ) {}
}
