<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.17
 *   protoc               — v6.33.5
 * Source: google/type/dayofweek.proto
 */

declare(strict_types=1);

namespace Google\Type;

/**
 * @api
 *
 * Represents a day of the week.
 */
enum DayOfWeek: int
{
    /** The day of the week is unspecified. */
    case DAY_OF_WEEK_UNSPECIFIED = 0;

    /** Monday */
    case MONDAY = 1;

    /** Tuesday */
    case TUESDAY = 2;

    /** Wednesday */
    case WEDNESDAY = 3;

    /** Thursday */
    case THURSDAY = 4;

    /** Friday */
    case FRIDAY = 5;

    /** Saturday */
    case SATURDAY = 6;

    /** Sunday */
    case SUNDAY = 7;
}
