<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.1
 *   protoc               — v6.33.5
 * Source: google/type/fraction.proto
 */

declare(strict_types=1);

namespace Google\Type;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Represents a fraction in terms of a numerator divided by a denominator.
 */
final readonly class Fraction
{
    /**
     * @param int $numerator The numerator in the fraction, e.g. 2 in 2/3.
     * @param int $denominator The value by which the numerator is divided, e.g. 3 in 2/3. Must be
     * positive.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int64T::T)]
        public int $numerator = 0,
        #[Reflection\Field(2, Reflection\Int64T::T)]
        public int $denominator = 0,
    ) {}
}
