<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: google/type/fraction.proto
 */

declare(strict_types=1);

namespace Google\Type;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class GoogleTypeFractionDescriptorRegistry implements Registry\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'Chpnb29nbGUvdHlwZS9mcmFjdGlvbi5wcm90bxILZ29vZ2xlLnR5cGUiSgoIRnJhY3Rpb24SHAoJbnVtZXJhdG9yGAEgASgDUgludW1lcmF0b3ISIAoLZGVub21pbmF0b3IYAiABKANSC2Rlbm9taW5hdG9yQmgKD2NvbS5nb29nbGUudHlwZUINRnJhY3Rpb25Qcm90b1ABSAFaPGdvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvdHlwZS9mcmFjdGlvbjtmcmFjdGlvbqICA0dUUEqOCAoGEgQOACABCrwECgEMEgMOABIysQQgQ29weXJpZ2h0IDIwMjUgR29vZ2xlIExMQwoKIExpY2Vuc2VkIHVuZGVyIHRoZSBBcGFjaGUgTGljZW5zZSwgVmVyc2lvbiAyLjAgKHRoZSAiTGljZW5zZSIpOwogeW91IG1heSBub3QgdXNlIHRoaXMgZmlsZSBleGNlcHQgaW4gY29tcGxpYW5jZSB3aXRoIHRoZSBMaWNlbnNlLgogWW91IG1heSBvYnRhaW4gYSBjb3B5IG9mIHRoZSBMaWNlbnNlIGF0CgogICAgIGh0dHA6Ly93d3cuYXBhY2hlLm9yZy9saWNlbnNlcy9MSUNFTlNFLTIuMAoKIFVubGVzcyByZXF1aXJlZCBieSBhcHBsaWNhYmxlIGxhdyBvciBhZ3JlZWQgdG8gaW4gd3JpdGluZywgc29mdHdhcmUKIGRpc3RyaWJ1dGVkIHVuZGVyIHRoZSBMaWNlbnNlIGlzIGRpc3RyaWJ1dGVkIG9uIGFuICJBUyBJUyIgQkFTSVMsCiBXSVRIT1VUIFdBUlJBTlRJRVMgT1IgQ09ORElUSU9OUyBPRiBBTlkgS0lORCwgZWl0aGVyIGV4cHJlc3Mgb3IgaW1wbGllZC4KIFNlZSB0aGUgTGljZW5zZSBmb3IgdGhlIHNwZWNpZmljIGxhbmd1YWdlIGdvdmVybmluZyBwZXJtaXNzaW9ucyBhbmQKIGxpbWl0YXRpb25zIHVuZGVyIHRoZSBMaWNlbnNlLgoKCAoBAhIDEAAUCggKAQgSAxIAUwoJCgIICxIDEgBTCggKAQgSAxMAIgoJCgIIChIDEwAiCggKAQgSAxQALgoJCgIICBIDFAAuCggKAQgSAxUAKAoJCgIIARIDFQAoCggKAQgSAxYAIQoJCgIIJBIDFgAhClUKAgQAEgQZACABGkkgUmVwcmVzZW50cyBhIGZyYWN0aW9uIGluIHRlcm1zIG9mIGEgbnVtZXJhdG9yIGRpdmlkZWQgYnkgYSBkZW5vbWluYXRvci4KCgoKAwQAARIDGQgQCjwKBAQAAgASAxsCFhovIFRoZSBudW1lcmF0b3IgaW4gdGhlIGZyYWN0aW9uLCBlLmcuIDIgaW4gMi8zLgoKDAoFBAACAAUSAxsCBwoMCgUEAAIAARIDGwgRCgwKBQQAAgADEgMbFBUKXQoEBAACARIDHwIYGlAgVGhlIHZhbHVlIGJ5IHdoaWNoIHRoZSBudW1lcmF0b3IgaXMgZGl2aWRlZCwgZS5nLiAzIGluIDIvMy4gTXVzdCBiZQogcG9zaXRpdmUuCgoMCgUEAAIBBRIDHwIHCgwKBQQAAgEBEgMfCBMKDAoFBAACAQMSAx8WF2IGcHJvdG8z';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'google/type/fraction.proto',
            messages: [
                new File\MessageDescriptor('google.type.Fraction', \Google\Type\Fraction::class),
            ],
        ));
    }
}
