<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.23
 *   protoc               — v6.33.5
 * Source: google/type/localized_text.proto
 */

declare(strict_types=1);

namespace Google\Type;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class GoogleTypeLocalizedTextDescriptorRegistry implements Registry\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'CiBnb29nbGUvdHlwZS9sb2NhbGl6ZWRfdGV4dC5wcm90bxILZ29vZ2xlLnR5cGUiSAoNTG9jYWxpemVkVGV4dBISCgR0ZXh0GAEgASgJUgR0ZXh0EiMKDWxhbmd1YWdlX2NvZGUYAiABKAlSDGxhbmd1YWdlQ29kZUJ8Cg9jb20uZ29vZ2xlLnR5cGVCEkxvY2FsaXplZFRleHRQcm90b1ABSAFaSGdvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvdHlwZS9sb2NhbGl6ZWRfdGV4dDtsb2NhbGl6ZWRfdGV4dPgBAaICA0dUUEr7CAoGEgQOACMBCrwECgEMEgMOABIysQQgQ29weXJpZ2h0IDIwMjUgR29vZ2xlIExMQwoKIExpY2Vuc2VkIHVuZGVyIHRoZSBBcGFjaGUgTGljZW5zZSwgVmVyc2lvbiAyLjAgKHRoZSAiTGljZW5zZSIpOwogeW91IG1heSBub3QgdXNlIHRoaXMgZmlsZSBleGNlcHQgaW4gY29tcGxpYW5jZSB3aXRoIHRoZSBMaWNlbnNlLgogWW91IG1heSBvYnRhaW4gYSBjb3B5IG9mIHRoZSBMaWNlbnNlIGF0CgogICAgIGh0dHA6Ly93d3cuYXBhY2hlLm9yZy9saWNlbnNlcy9MSUNFTlNFLTIuMAoKIFVubGVzcyByZXF1aXJlZCBieSBhcHBsaWNhYmxlIGxhdyBvciBhZ3JlZWQgdG8gaW4gd3JpdGluZywgc29mdHdhcmUKIGRpc3RyaWJ1dGVkIHVuZGVyIHRoZSBMaWNlbnNlIGlzIGRpc3RyaWJ1dGVkIG9uIGFuICJBUyBJUyIgQkFTSVMsCiBXSVRIT1VUIFdBUlJBTlRJRVMgT1IgQ09ORElUSU9OUyBPRiBBTlkgS0lORCwgZWl0aGVyIGV4cHJlc3Mgb3IgaW1wbGllZC4KIFNlZSB0aGUgTGljZW5zZSBmb3IgdGhlIHNwZWNpZmljIGxhbmd1YWdlIGdvdmVybmluZyBwZXJtaXNzaW9ucyBhbmQKIGxpbWl0YXRpb25zIHVuZGVyIHRoZSBMaWNlbnNlLgoKCAoBAhIDEAAUCggKAQgSAxIAHwoJCgIIHxIDEgAfCggKAQgSAxMAXwoJCgIICxIDEwBfCggKAQgSAxQAIgoJCgIIChIDFAAiCggKAQgSAxUAMwoJCgIICBIDFQAzCggKAQgSAxYAKAoJCgIIARIDFgAoCggKAQgSAxcAIQoJCgIIJBIDFwAhCkMKAgQAEgQaACMBGjcgTG9jYWxpemVkIHZhcmlhbnQgb2YgYSB0ZXh0IGluIGEgcGFydGljdWxhciBsYW5ndWFnZS4KCgoKAwQAARIDGggVClcKBAQAAgASAxwCEhpKIExvY2FsaXplZCBzdHJpbmcgaW4gdGhlIGxhbmd1YWdlIGNvcnJlc3BvbmRpbmcgdG8gYGxhbmd1YWdlX2NvZGUnIGJlbG93LgoKDAoFBAACAAUSAxwCCAoMCgUEAAIAARIDHAkNCgwKBQQAAgADEgMcEBEKqwEKBAQAAgESAyICGxqdASBUaGUgdGV4dCdzIEJDUC00NyBsYW5ndWFnZSBjb2RlLCBzdWNoIGFzICJlbi1VUyIgb3IgInNyLUxhdG4iLgoKIEZvciBtb3JlIGluZm9ybWF0aW9uLCBzZWUKIGh0dHA6Ly93d3cudW5pY29kZS5vcmcvcmVwb3J0cy90cjM1LyNVbmljb2RlX2xvY2FsZV9pZGVudGlmaWVyLgoKDAoFBAACAQUSAyICCAoMCgUEAAIBARIDIgkWCgwKBQQAAgEDEgMiGRpiBnByb3RvMw==';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'google/type/localized_text.proto',
            messages: [
                new File\MessageDescriptor('google.type.LocalizedText', \Google\Type\LocalizedText::class),
            ],
        ));
    }
}
