<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.13
 *   protoc               — v6.33.5
 * Source: google/type/fraction.proto
 */

declare(strict_types=1);

namespace Google\Type;

use Override;
use Thesis\Protobuf\Pool;
use Thesis\Protobuf\Pool\File;

/**
 * @api
 */
final readonly class GoogleTypeFractionDescriptorRegistry implements Pool\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'Chpnb29nbGUvdHlwZS9mcmFjdGlvbi5wcm90bxILZ29vZ2xlLnR5cGUiSgoIRnJhY3Rpb24SHAoJbnVtZXJhdG9yGAEgASgDUgludW1lcmF0b3ISIAoLZGVub21pbmF0b3IYAiABKANSC2Rlbm9taW5hdG9yQmkKD2NvbS5nb29nbGUudHlwZUINRnJhY3Rpb25Qcm90b1ABWjxnb29nbGUuZ29sYW5nLm9yZy9nZW5wcm90by9nb29nbGVhcGlzL3R5cGUvZnJhY3Rpb247ZnJhY3Rpb274AQGiAgNHVFBKjggKBhIEDgAgAQq8BAoBDBIDDgASMrEEIENvcHlyaWdodCAyMDI1IEdvb2dsZSBMTEMKCiBMaWNlbnNlZCB1bmRlciB0aGUgQXBhY2hlIExpY2Vuc2UsIFZlcnNpb24gMi4wICh0aGUgIkxpY2Vuc2UiKTsKIHlvdSBtYXkgbm90IHVzZSB0aGlzIGZpbGUgZXhjZXB0IGluIGNvbXBsaWFuY2Ugd2l0aCB0aGUgTGljZW5zZS4KIFlvdSBtYXkgb2J0YWluIGEgY29weSBvZiB0aGUgTGljZW5zZSBhdAoKICAgICBodHRwOi8vd3d3LmFwYWNoZS5vcmcvbGljZW5zZXMvTElDRU5TRS0yLjAKCiBVbmxlc3MgcmVxdWlyZWQgYnkgYXBwbGljYWJsZSBsYXcgb3IgYWdyZWVkIHRvIGluIHdyaXRpbmcsIHNvZnR3YXJlCiBkaXN0cmlidXRlZCB1bmRlciB0aGUgTGljZW5zZSBpcyBkaXN0cmlidXRlZCBvbiBhbiAiQVMgSVMiIEJBU0lTLAogV0lUSE9VVCBXQVJSQU5USUVTIE9SIENPTkRJVElPTlMgT0YgQU5ZIEtJTkQsIGVpdGhlciBleHByZXNzIG9yIGltcGxpZWQuCiBTZWUgdGhlIExpY2Vuc2UgZm9yIHRoZSBzcGVjaWZpYyBsYW5ndWFnZSBnb3Zlcm5pbmcgcGVybWlzc2lvbnMgYW5kCiBsaW1pdGF0aW9ucyB1bmRlciB0aGUgTGljZW5zZS4KCggKAQISAxAAFAoICgEIEgMSAFMKCQoCCAsSAxIAUwoICgEIEgMTACIKCQoCCAoSAxMAIgoICgEIEgMUAC4KCQoCCAgSAxQALgoICgEIEgMVACgKCQoCCAESAxUAKAoICgEIEgMWACEKCQoCCCQSAxYAIQpVCgIEABIEGQAgARpJIFJlcHJlc2VudHMgYSBmcmFjdGlvbiBpbiB0ZXJtcyBvZiBhIG51bWVyYXRvciBkaXZpZGVkIGJ5IGEgZGVub21pbmF0b3IuCgoKCgMEAAESAxkIEAo8CgQEAAIAEgMbAhYaLyBUaGUgbnVtZXJhdG9yIGluIHRoZSBmcmFjdGlvbiwgZS5nLiAyIGluIDIvMy4KCgwKBQQAAgAFEgMbAgcKDAoFBAACAAESAxsIEQoMCgUEAAIAAxIDGxQVCl0KBAQAAgESAx8CGBpQIFRoZSB2YWx1ZSBieSB3aGljaCB0aGUgbnVtZXJhdG9yIGlzIGRpdmlkZWQsIGUuZy4gMyBpbiAyLzMuIE11c3QgYmUKIHBvc2l0aXZlLgoKDAoFBAACAQUSAx8CBwoMCgUEAAIBARIDHwgTCgwKBQQAAgEDEgMfFhdiBnByb3RvMw==';

    #[Override]
    public function register(Pool\Registry $pool): void
    {
        $pool->add(Pool\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'google/type/fraction.proto',
            messages: [
                new File\MessageDescriptor('google.type.Fraction', \Google\Type\Fraction::class),
            ],
        ));
    }
}
