<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.13
 *   protoc               — v6.33.5
 * Source: google/type/localized_text.proto
 */

declare(strict_types=1);

namespace Google\Type;

use Override;
use Thesis\Protobuf\Pool;
use Thesis\Protobuf\Pool\File;

/**
 * @api
 */
final readonly class GoogleTypeLocalizedTextDescriptorRegistry implements Pool\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'CiBnb29nbGUvdHlwZS9sb2NhbGl6ZWRfdGV4dC5wcm90bxILZ29vZ2xlLnR5cGUiSAoNTG9jYWxpemVkVGV4dBISCgR0ZXh0GAEgASgJUgR0ZXh0EiMKDWxhbmd1YWdlX2NvZGUYAiABKAlSDGxhbmd1YWdlQ29kZUJ6Cg9jb20uZ29vZ2xlLnR5cGVCEkxvY2FsaXplZFRleHRQcm90b1ABWkhnb29nbGUuZ29sYW5nLm9yZy9nZW5wcm90by9nb29nbGVhcGlzL3R5cGUvbG9jYWxpemVkX3RleHQ7bG9jYWxpemVkX3RleHT4AQGiAgNHVFBK+wgKBhIEDgAjAQq8BAoBDBIDDgASMrEEIENvcHlyaWdodCAyMDI1IEdvb2dsZSBMTEMKCiBMaWNlbnNlZCB1bmRlciB0aGUgQXBhY2hlIExpY2Vuc2UsIFZlcnNpb24gMi4wICh0aGUgIkxpY2Vuc2UiKTsKIHlvdSBtYXkgbm90IHVzZSB0aGlzIGZpbGUgZXhjZXB0IGluIGNvbXBsaWFuY2Ugd2l0aCB0aGUgTGljZW5zZS4KIFlvdSBtYXkgb2J0YWluIGEgY29weSBvZiB0aGUgTGljZW5zZSBhdAoKICAgICBodHRwOi8vd3d3LmFwYWNoZS5vcmcvbGljZW5zZXMvTElDRU5TRS0yLjAKCiBVbmxlc3MgcmVxdWlyZWQgYnkgYXBwbGljYWJsZSBsYXcgb3IgYWdyZWVkIHRvIGluIHdyaXRpbmcsIHNvZnR3YXJlCiBkaXN0cmlidXRlZCB1bmRlciB0aGUgTGljZW5zZSBpcyBkaXN0cmlidXRlZCBvbiBhbiAiQVMgSVMiIEJBU0lTLAogV0lUSE9VVCBXQVJSQU5USUVTIE9SIENPTkRJVElPTlMgT0YgQU5ZIEtJTkQsIGVpdGhlciBleHByZXNzIG9yIGltcGxpZWQuCiBTZWUgdGhlIExpY2Vuc2UgZm9yIHRoZSBzcGVjaWZpYyBsYW5ndWFnZSBnb3Zlcm5pbmcgcGVybWlzc2lvbnMgYW5kCiBsaW1pdGF0aW9ucyB1bmRlciB0aGUgTGljZW5zZS4KCggKAQISAxAAFAoICgEIEgMSAB8KCQoCCB8SAxIAHwoICgEIEgMTAF8KCQoCCAsSAxMAXwoICgEIEgMUACIKCQoCCAoSAxQAIgoICgEIEgMVADMKCQoCCAgSAxUAMwoICgEIEgMWACgKCQoCCAESAxYAKAoICgEIEgMXACEKCQoCCCQSAxcAIQpDCgIEABIEGgAjARo3IExvY2FsaXplZCB2YXJpYW50IG9mIGEgdGV4dCBpbiBhIHBhcnRpY3VsYXIgbGFuZ3VhZ2UuCgoKCgMEAAESAxoIFQpXCgQEAAIAEgMcAhIaSiBMb2NhbGl6ZWQgc3RyaW5nIGluIHRoZSBsYW5ndWFnZSBjb3JyZXNwb25kaW5nIHRvIGBsYW5ndWFnZV9jb2RlJyBiZWxvdy4KCgwKBQQAAgAFEgMcAggKDAoFBAACAAESAxwJDQoMCgUEAAIAAxIDHBARCqsBCgQEAAIBEgMiAhsanQEgVGhlIHRleHQncyBCQ1AtNDcgbGFuZ3VhZ2UgY29kZSwgc3VjaCBhcyAiZW4tVVMiIG9yICJzci1MYXRuIi4KCiBGb3IgbW9yZSBpbmZvcm1hdGlvbiwgc2VlCiBodHRwOi8vd3d3LnVuaWNvZGUub3JnL3JlcG9ydHMvdHIzNS8jVW5pY29kZV9sb2NhbGVfaWRlbnRpZmllci4KCgwKBQQAAgEFEgMiAggKDAoFBAACAQESAyIJFgoMCgUEAAIBAxIDIhkaYgZwcm90bzM=';

    #[Override]
    public function register(Pool\Registry $pool): void
    {
        $pool->add(Pool\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'google/type/localized_text.proto',
            messages: [
                new File\MessageDescriptor('google.type.LocalizedText', \Google\Type\LocalizedText::class),
            ],
        ));
    }
}
