<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.18
 *   protoc               — v6.33.5
 * Source: google/type/interval.proto
 */

declare(strict_types=1);

namespace Google\Type;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Represents a time interval, encoded as a Timestamp start (inclusive) and a
 * Timestamp end (exclusive).
 *
 * The start must be less than or equal to the end.
 * When the start equals the end, the interval is empty (matches no time).
 * When both start and end are unspecified, the interval matches any time.
 */
final readonly class Interval
{
    /**
     * @param ?\Google\Protobuf\Timestamp $startTime Optional. Inclusive start of the interval.
     *
     * If specified, a Timestamp matching this interval will have to be the same
     * or after the start.
     * @param ?\Google\Protobuf\Timestamp $endTime Optional. Exclusive end of the interval.
     *
     * If specified, a Timestamp matching this interval will have to be before the
     * end.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Google\Protobuf\Timestamp::class))]
        public ?\Google\Protobuf\Timestamp $startTime = null,
        #[Reflection\Field(2, new Reflection\ObjectT(\Google\Protobuf\Timestamp::class))]
        public ?\Google\Protobuf\Timestamp $endTime = null,
    ) {}
}
