<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.2
 *   protoc               — v6.33.5
 * Source: google/type/latlng.proto
 */

declare(strict_types=1);

namespace Google\Type;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * An object that represents a latitude/longitude pair. This is expressed as a
 * pair of doubles to represent degrees latitude and degrees longitude. Unless
 * specified otherwise, this must conform to the
 * <a href="http://www.unoosa.org/pdf/icg/2012/template/WGS_84.pdf">WGS84
 * standard</a>. Values must be within normalized ranges.
 */
final readonly class LatLng
{
    /**
     * @param float $latitude The latitude in degrees. It must be in the range [-90.0, +90.0].
     * @param float $longitude The longitude in degrees. It must be in the range [-180.0, +180.0].
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\DoubleT::T)]
        public float $latitude = 0,
        #[Reflection\Field(2, Reflection\DoubleT::T)]
        public float $longitude = 0,
    ) {}
}
