<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.24
 *   protoc               — v6.33.5
 * Source: google/type/localized_text.proto
 */

declare(strict_types=1);

namespace Google\Type;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Localized variant of a text in a particular language.
 */
final readonly class LocalizedText
{
    /**
     * @param string $text Localized string in the language corresponding to `language_code' below.
     * @param string $languageCode The text's BCP-47 language code, such as "en-US" or "sr-Latn".
     *
     * For more information, see
     * http://www.unicode.org/reports/tr35/#Unicode_locale_identifier.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $text = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $languageCode = '',
    ) {}
}
