<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: google/type/money.proto
 */

declare(strict_types=1);

namespace Google\Type;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Represents an amount of money with its currency type.
 */
final readonly class Money
{
    /**
     * @param string $currencyCode The three-letter currency code defined in ISO 4217.
     * @param \BcMath\Number $units The whole units of the amount.
     * For example if `currencyCode` is `"USD"`, then 1 unit is one US dollar.
     * @param int $nanos Number of nano (10^-9) units of the amount.
     * The value must be between -999,999,999 and +999,999,999 inclusive.
     * If `units` is positive, `nanos` must be positive or zero.
     * If `units` is zero, `nanos` can be positive, zero, or negative.
     * If `units` is negative, `nanos` must be negative or zero.
     * For example $-1.75 is represented as `units`=-1 and `nanos`=-750,000,000.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $currencyCode = '',
        #[Reflection\Field(2, Reflection\Int64T::T)]
        public \BcMath\Number $units = new \BcMath\Number(0),
        #[Reflection\Field(3, Reflection\Int32T::T)]
        public int $nanos = 0,
    ) {}
}
