<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.13
 *   protoc               — v6.33.5
 * Source: google/type/month.proto
 */

declare(strict_types=1);

namespace Google\Type;

/**
 * @api
 *
 * Represents a month in the Gregorian calendar.
 */
enum Month: int
{
    /** The unspecified month. */
    case MONTH_UNSPECIFIED = 0;

    /** The month of January. */
    case JANUARY = 1;

    /** The month of February. */
    case FEBRUARY = 2;

    /** The month of March. */
    case MARCH = 3;

    /** The month of April. */
    case APRIL = 4;

    /** The month of May. */
    case MAY = 5;

    /** The month of June. */
    case JUNE = 6;

    /** The month of July. */
    case JULY = 7;

    /** The month of August. */
    case AUGUST = 8;

    /** The month of September. */
    case SEPTEMBER = 9;

    /** The month of October. */
    case OCTOBER = 10;

    /** The month of November. */
    case NOVEMBER = 11;

    /** The month of December. */
    case DECEMBER = 12;
}
