<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.18
 *   protoc               — v6.33.5
 * Source: google/type/datetime.proto
 */

declare(strict_types=1);

namespace Google\Type;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Represents a time zone from the
 * [IANA Time Zone Database](https://www.iana.org/time-zones).
 */
final readonly class TimeZone
{
    /**
     * @param string $id IANA Time Zone Database time zone, e.g. "America/New_York".
     * @param string $version Optional. IANA Time Zone Database version number, e.g. "2019a".
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $id = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $version = '',
    ) {}
}
