<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.17
 *   protoc               — v6.33.5
 * Source: google/type/timeofday.proto
 */

declare(strict_types=1);

namespace Google\Type;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Represents a time of day. The date and time zone are either not significant
 * or are specified elsewhere. An API may choose to allow leap seconds. Related
 * types are [google.type.Date][google.type.Date] and
 * `google.protobuf.Timestamp`.
 */
final readonly class TimeOfDay
{
    /**
     * @param int $hours Hours of day in 24 hour format. Should be from 0 to 23. An API may choose
     * to allow the value "24:00:00" for scenarios like business closing time.
     * @param int $minutes Minutes of hour of day. Must be from 0 to 59.
     * @param int $seconds Seconds of minutes of the time. Must normally be from 0 to 59. An API may
     * allow the value 60 if it allows leap-seconds.
     * @param int $nanos Fractions of seconds in nanoseconds. Must be from 0 to 999,999,999.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int32T::T)]
        public int $hours = 0,
        #[Reflection\Field(2, Reflection\Int32T::T)]
        public int $minutes = 0,
        #[Reflection\Field(3, Reflection\Int32T::T)]
        public int $seconds = 0,
        #[Reflection\Field(4, Reflection\Int32T::T)]
        public int $nanos = 0,
    ) {}
}
